-- Initial schema

CREATE TABLE ANNOS (
    ID BIGINT PRIMARY KEY,
    NIMI VARCHAR(32) NOT NULL,
    KUVAUS VARCHAR(255) DEFAULT '',
    HINTA DECIMAL(10,5) NOT NULL,
    TYYPPI_ID BIGINT NOT NULL
);

CREATE TABLE TYYPPI (
    ID BIGINT PRIMARY KEY,
    NIMI VARCHAR(32) NOT NULL
);

ALTER TABLE ANNOS
    ADD CONSTRAINT FK_ANNOS_TYYPPI
    FOREIGN KEY (TYYPPI_ID) REFERENCES TYYPPI(ID)
    ON DELETE CASCADE;